<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>drive-and-deliver</artifactId>
        <groupId>com.carrefour</groupId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>


    <artifactId>drive-and-deliver-infra-kafka</artifactId>
    <packaging>jar</packaging>
    <name>drive-and-deliver-infra-kafka</name>
    <description>La couche infra rest héberge le code</description>

    <properties>
        <sonar.skip>false</sonar.skip>
        <reactor-test.version>3.5.3</reactor-test.version>
        <wiremock-standalone.version>2.26.0</wiremock-standalone.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>com.carrefour</groupId>
            <artifactId>drive-and-deliver-domain</artifactId>
        </dependency>

        <!-- Spring Kafka -->
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>

        <!-- Reactive Kafka Streams support -->
        <dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka-streams</artifactId>
            <scope>provided</scope>
        </dependency>

    </dependencies>

</project>
